delete from account;
delete from dd_my_accounts__c;
delete from dms_question__c;
delete from dms_survey__c;
delete from _trigger_log;
delete from dd_survey_submission__c;
delete from dms_survey_result__c;
delete from contact;
delete from dd_assigned_goal__c;